services:
  sample:
    image: ghcr.io/tawmy/aspnetcoreextensions:1.0.0
    restart: unless-stopped
    environment:
      LOGGING__LOGLEVEL__DEFAULT: Information
      LOGGING__LOGLEVEL__MICROSOFT.ASPNETCORE: Warning
