// <auto-generated />
using System;
using AspNetCoreExtensions.Keycloak.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspNetCoreExtensions.Keycloak.Db.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251206181022_UserSessions")]
    partial class UserSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreExtensions.Keycloak.Db.Models.UserSession", b =>
                {
                    b.Property<Guid>("Sid")
                        .HasColumnType("uuid")
                        .HasColumnName("sid");

                    b.Property<string>("AuthenticationScheme")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("authentication_scheme");

                    b.Property<string>("Principal")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("principal");

                    b.HasKey("Sid")
                        .HasName("pk_user_sessions");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("AspNetCoreExtensions.Keycloak.Db.Models.UserSession", b =>
                {
                    b.OwnsOne("Microsoft.AspNetCore.Authentication.AuthenticationProperties", "Properties", b1 =>
                        {
                            b1.Property<Guid>("UserSessionSid");

                            b1.Property<bool?>("AllowRefresh");

                            b1.Property<DateTimeOffset?>("ExpiresUtc");

                            b1.Property<bool>("IsPersistent");

                            b1.Property<DateTimeOffset?>("IssuedUtc");

                            b1.Property<string>("RedirectUri");

                            b1.HasKey("UserSessionSid");

                            b1.ToTable("user_sessions");

                            b1.ToJson("properties");

                            b1.WithOwner()
                                .HasForeignKey("UserSessionSid")
                                .HasConstraintName("fk_user_sessions_user_sessions_sid");
                        });

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
