// <auto-generated />
using System;
using AspNetCoreExtensions.Keycloak.Db;
using AspNetCoreExtensions.OpenIdConnect.Keycloak.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspNetCoreExtensions.Keycloak.Db.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreExtensions.Keycloak.Db.Models.UserSession", b =>
                {
                    b.Property<Guid>("Sid")
                        .HasColumnType("uuid")
                        .HasColumnName("sid");

                    b.Property<string>("AuthenticationScheme")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("authentication_scheme");

                    b.Property<string>("Principal")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("principal");

                    b.Property<string>("Properties")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("properties");

                    b.HasKey("Sid")
                        .HasName("pk_user_sessions");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("AspNetCoreExtensions.Keycloak.Db.Models.UserToken", b =>
                {
                    b.Property<Guid>("Sub")
                        .HasColumnType("uuid")
                        .HasColumnName("sub");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("character varying(32768)")
                        .HasColumnName("access_token");

                    b.Property<string>("AccessTokenType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("access_token_type");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("client_id");

                    b.Property<string>("DPoPJsonWebKey")
                        .HasMaxLength(32768)
                        .HasColumnType("character varying(32768)")
                        .HasColumnName("d_po_p_json_web_key");

                    b.Property<DateTimeOffset>("Expiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration");

                    b.Property<string>("IdentityToken")
                        .HasMaxLength(32768)
                        .HasColumnType("character varying(32768)")
                        .HasColumnName("identity_token");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(32768)
                        .HasColumnType("character varying(32768)")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("scope");

                    b.HasKey("Sub")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
